services:
    fbaroni.base.manager:
        class: Fbaroni\Bundle\BaseBundle\Manager\Manager
        abstract:  true
        arguments: ['@event_dispatcher' ,'@logger' ,'@security.token_storage' ,'@session', '@knp_paginator' ]

    fbaroni.base.doctrine_repository:
        class: Fbaroni\Bundle\BaseBundle\Repository\DoctrineEntityRepository
        abstract:  true
        arguments: ['@doctrine.orm.default_entity_manager']

    fbaroni.base.form_handler:
        class: Fbaroni\Bundle\BaseBundle\Form\Handler\FormHandler
        abstract:  true
        calls:
            - [setRequest, ['@request']]
            - [setValidator, ['@validator']]
